### ISSUE TITLE
在typecho webstack中使用不显示内容

### ISSUE THREAD

**Issue by shj37** [YianAndCode/Comment2Fanwan#1]
![({BT}(_IEK295FK{%RYH0%G](https://user-images.githubusercontent.com/8279674/120160091-71e14080-c228-11eb-8f54-9aab53ee1e8c.png)

谢谢

**Comment by YianAndCode** [comment]
可以贴一下饭碗警告的“通知正文”吗？

![image](https://user-images.githubusercontent.com/6998693/120161110-8a058f80-c229-11eb-9390-599f39390528.png)

另外 Typecho 和 PHP 的版本最好也提供一下，我这里用最新版的 Typeco 在 PHP 7.4 和 PHP 8.0 都没复现

**Comment by shj37** [comment]
![0QZ5G9 5 XOP`` }RA9F536](https://user-images.githubusercontent.com/8279674/120172461-a8718800-c235-11eb-9193-72505e638093.png)


> 可以贴一下饭碗警告的“通知正文”吗？
> 
> ![image](https://user-images.githubusercontent.com/6998693/120161110-8a058f80-c229-11eb-9390-599f39390528.png)
> 
> 另外 Typecho 和 PHP 的版本最好也提供一下，我这里用最新版的 Typeco 在 PHP 7.4 和 PHP 8.0 都没复现

**Comment by YianAndCode** [comment]
我还是没能复现这个问题，辛苦到饭碗控制台的 `转发记录` 里找到有问题的那条，拉到最下面，把 `源请求` 下载下来然后贴出来

![image](https://user-images.githubusercontent.com/6998693/120525785-191dcd80-c40b-11eb-98eb-7ad94503bcac.png)

**Comment by shj37** [comment]
@YianAndCode 

POST https://fwalert.com/xxx HTTP/1.1
content-type: application/json
content-length: 153
server-port: 443
server-addr: 172.16.0.7
server-name: fwalert.com
server-protocol: HTTP/1.0
scheme: https
x-forwarded-proto: https
x-forwarded-for: 101.32.185.66
x-real-port: 59008
x-real-ip: 101.32.185.66
host: fwalert.com
connection: upgrade
cookie: fwalert:session=session:d648cffe-84d1-49ce-9cb3-bcb6ef4470e4; fwalert:session.sig=q2jtuDh7iMo4BfCioJn5dcNblRY

{"title":"剑桥大学","comment":"test1","author":"admin","created_at":"2021-05-31 13:37:38","url":"https:\/\/www.liuxuelianjie.com\/index.php\/1.html"}

**Comment by YianAndCode** [comment]
@shj37 感谢反馈，看起来请求是正常的，我联系下 Fw 的同学看看是什么原因导致的

**Comment by shj37** [comment]
> @shj37 感谢反馈，看起来请求是正常的，我联系下 Fw 的同学看看是什么原因导致的

@YianAndCode 还没解决？

**Comment by YianAndCode** [comment]
@shj37 复现不出来，你那现在还能复现出来吗？我试着在上面的链接留过言，你看下收到的邮件是否正常，如果正常，那可能是当时 fw 刚好抽风了

**Comment by shj37** [comment]
@YianAndCode 还是不行，一样的问题, 你5天前留的言也不行
