### ISSUE TITLE
ReadMe里的参考截图挂了，在screenshots里的也挂了，不知道有没有一个饭碗规则配置的例子可以参考

### ISSUE THREAD

**Issue by coderZoe** [YianAndCode/Comment2Fanwan#2]

**Comment by YianAndCode** [comment]
GitHub 网页图片用的是 raw.githubusercontent.com 这个域名，在国内可能没法打开，可以把整个项目 clone 到本地查看

**Comment by coderZoe** [comment]
> GitHub 网页图片用的是 raw.githubusercontent.com 这个域名，在国内可能没法打开，可以把整个项目 clone 到本地查看

感谢回复，但是按照教程那么多还是没收到邮件和短信，目前是typeecho1.2 PHP是7.3.15 是PHP版本过低吗

**Comment by YianAndCode** [comment]
版本应该没问题，可以到饭碗控制面板看看有没有转发记录，如果有那可能是饭碗的通知规则没设置对；如果没有就看下 php-fpm 的 error log 有没有错误信息

**Comment by coderZoe** [comment]
饭碗规则的配置如下：
https://coderzoe.oss-cn-beijing.aliyuncs.com/202208272357470.png
https://coderzoe.oss-cn-beijing.aliyuncs.com/202208272358995.png
https://coderzoe.oss-cn-beijing.aliyuncs.com/202208272358534.png

php-fpm应该是没有error的，信息如下（刚刚重启过，再之前的日志就是很多天前的了）
https://coderzoe.oss-cn-beijing.aliyuncs.com/202208272359072.png
